ecd = {
    "0000": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_VER",
        "Coluna_3": "COD_FIN",
        "Coluna_4": "DT_INI",
        "Coluna_5": "DT_FIN",
        "Coluna_6": "NOME",
        "Coluna_7": "CNPJ",
        "Coluna_8": "CPF",
        "Coluna_9": "UF",
        "Coluna_10": "IE",
        "Coluna_11": "COD_MUN",
        "Coluna_12": "IM",
        "Coluna_13": "SUFRAMA",
        "Coluna_14": "IND_PERFIL",
        "Coluna_15": "IND_ATIV"
    },
    "0001": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_MOV"
    },
    "0002": {
        "Coluna_1": "REG",
        "Coluna_2": "CLAS_ESTAB_IND"
    },
    "0005": {
        "Coluna_1": "REG",
        "Coluna_2": "FANTASIA",
        "Coluna_3": "CEP",
        "Coluna_4": "END",
        "Coluna_5": "NUM",
        "Coluna_6": "COMPL",
        "Coluna_7": "BAIRRO",
        "Coluna_8": "FONE",
        "Coluna_9": "FAX",
        "Coluna_10": "EMAIL"
    },
    "0015": {
        "Coluna_1": "REG",
        "Coluna_2": "UF_ST",
        "Coluna_3": "IE_ST"
    },
    "0100": {
        "Coluna_1": "REG",
        "Coluna_2": "NOME",
        "Coluna_3": "CPF",
        "Coluna_4": "CRC",
        "Coluna_5": "CNPJ",
        "Coluna_6": "CEP",
        "Coluna_7": "END",
        "Coluna_8": "NUM",
        "Coluna_9": "COMPL",
        "Coluna_10": "BAIRRO",
        "Coluna_11": "FONE",
        "Coluna_12": "FAX",
        "Coluna_13": "EMAIL",
        "Coluna_14": "COD_MU N"
    },
    "0150": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PART",
        "Coluna_3": "NOME",
        "Coluna_4": "COD_PAIS",
        "Coluna_5": "CNPJ",
        "Coluna_6": "CPF",
        "Coluna_7": "IE",
        "Coluna_8": "COD_MUN",
        "Coluna_9": "SUFRAMA",
        "Coluna_10": "END",
        "Coluna_11": "NUM",
        "Coluna_12": "COMPL",
        "Coluna_13": "BAIRRO"
    },
    "0175": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_ALT",
        "Coluna_3": "NR_CAMPO",
        "Coluna_4": "CONT_ANT"
    },
    "0190": {
        "Coluna_1": "REG",
        "Coluna_2": "UNID",
        "Coluna_3": "DESCR"
    },
    "0200": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM",
        "Coluna_3": "DESCR_ITEM",
        "Coluna_4": "COD_BARRA",
        "Coluna_5": "COD_ANT_ITEM",
        "Coluna_6": "UNID_INV",
        "Coluna_7": "TIPO_ITEM",
        "Coluna_8": "COD_NCM",
        "Coluna_9": "EX_IPI",
        "Coluna_10": "COD_GEN",
        "Coluna_11": "COD_LST",
        "Coluna_12": "ALIQ_ICMS",
        "Coluna_13": "CEST"
    },
    "0205": {
        "Coluna_1": "REG",
        "Coluna_2": "DESCR_ANT_ITEM",
        "Coluna_3": "DT_INI",
        "Coluna_4": "DT_FIM",
        "Coluna_5": "COD_ANT_ITEM"
    },
    "0206": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_COMB"
    },
    "0210": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM_COMP",
        "Coluna_3": "QTD_COMP",
        "Coluna_4": "PERDA"
    },
    "0220": {
        "Coluna_1": "REG",
        "Coluna_2": "UNID_CONV",
        "Coluna_3": "FAT_CONV",
        "Coluna_4": "COD_BARRA"
    },
    "0221": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM_ ATOMICO",
        "Coluna_3": "QTD_CONTI DA"
    },
    "0300": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_IND_BEM",
        "Coluna_3": "IDENT_MERC",
        "Coluna_4": "DESCR_ITEM",
        "Coluna_5": "COD_PRNC",
        "Coluna_6": "COD_CTA",
        "Coluna_7": "NR_PARC"
    },
    "0305": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_CCUS",
        "Coluna_3": "FUNC",
        "Coluna_4": "VIDA_UTIL"
    },
    "0400": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_NAT",
        "Coluna_3": "DESCR_NAT"
    },
    "0450": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_INF",
        "Coluna_3": "TXT"
    },
    "0460": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_OBS",
        "Coluna_3": "TXT"
    },
    "0500": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_ALT",
        "Coluna_3": "COD_ NAT_CC",
        "Coluna_4": "IND_CTA",
        "Coluna_5": "N\u00cdVEL",
        "Coluna_6": "COD_CTA",
        "Coluna_7": "NOME_CTA"
    },
    "0600": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_ALT",
        "Coluna_3": "COD_CCUS",
        "Coluna_4": "CCUS"
    },
    "0990": {
        "Coluna_1": "REG",
        "Coluna_2": "QTD_LIN_0"
    },
    "1001": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_MOV"
    },
    "1010": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_EXP",
        "Coluna_3": "IND_CCRF",
        "Coluna_4": "IND_COMB",
        "Coluna_5": "IND_USINA",
        "Coluna_6": "IND_VA",
        "Coluna_7": "IND_EE",
        "Coluna_8": "IND_CART",
        "Coluna_9": "IND_FORM",
        "Coluna_10": "IND_AER",
        "Coluna_11": "IND_GIAF1",
        "Coluna_12": "IND_GIAF3",
        "Coluna_13": "IND_GIAF4",
        "Coluna_14": "IND_REST_RESSARC _COMPL_ICMS"
    },
    "1100": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_DOC",
        "Coluna_3": "NRO_DE",
        "Coluna_4": "DT_DE",
        "Coluna_5": "NAT_EXP",
        "Coluna_6": "NRO_RE",
        "Coluna_7": "DT_RE",
        "Coluna_8": "CHC_EMB",
        "Coluna_9": "DT_CHC",
        "Coluna_10": "DT_AVB",
        "Coluna_11": "TP_CHC",
        "Coluna_12": "PAIS"
    },
    "1105": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "SERIE",
        "Coluna_4": "NUM_DOC",
        "Coluna_5": "CHV_NFE",
        "Coluna_6": "DT DOC _",
        "Coluna_7": "COD_ITEM"
    },
    "1110": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PART",
        "Coluna_3": "COD_MOD",
        "Coluna_4": "NUM_DOC",
        "Coluna_5": "DT_DOC",
        "Coluna_6": "CHV_NFE",
        "Coluna_7": "NR_ MEMO",
        "Coluna_8": "QTD",
        "Coluna_9": "UNID"
    },
    "1200": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_AJ_APUR",
        "Coluna_3": "SLD_CRED",
        "Coluna_4": "CRED_APR",
        "Coluna_5": "CRED_RECEB",
        "Coluna_6": "CRED_UTIL",
        "Coluna_7": "SLD_CRED_FIM"
    },
    "1210": {
        "Coluna_1": "REG",
        "Coluna_2": "TIPO_UTIL",
        "Coluna_3": "NR_DOC",
        "Coluna_4": "VL_CRED_UTIL",
        "Coluna_5": "CHV_DOCe"
    },
    "1250": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_CREDITO_ICMS_OP",
        "Coluna_3": "VL_ICMS_ST_REST",
        "Coluna_4": "VL_FCP_ST_REST",
        "Coluna_5": "VL_ICMS_ST_COMPL",
        "Coluna_6": "VL_FCP_ST_COMPL"
    },
    "1255": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOT_REST_COMPL",
        "Coluna_3": "VL_CREDITO_ICMS_OP_MOT",
        "Coluna_4": "VL_ICMS_ST_REST_MOT",
        "Coluna_5": "VL_FCP_ST_REST_MOT",
        "Coluna_6": "VL_ICMS_ST_COMPL_MOT",
        "Coluna_7": "VL_FCP_ST_COMPL_MOT"
    },
    "1300": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM",
        "Coluna_3": "DT_FECH",
        "Coluna_4": "ESTQ_ABERT",
        "Coluna_5": "VOL_ENTR",
        "Coluna_6": "VOL_DISP",
        "Coluna_7": "VOL_SAIDAS",
        "Coluna_8": "ESTQ_ESCR",
        "Coluna_9": "VAL_AJ_PERDA",
        "Coluna_10": "VAL_AJ_GANHO",
        "Coluna_11": "FECH_FISICO"
    },
    "1310": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_TANQUE",
        "Coluna_3": "ESTQ_ABERT",
        "Coluna_4": "VOL_ENTR",
        "Coluna_5": "VOL_DISP",
        "Coluna_6": "VOL_SAIDAS",
        "Coluna_7": "ESTQ_ESCR",
        "Coluna_8": "VAL_AJ_PERDA",
        "Coluna_9": "VAL_AJ_GANHO",
        "Coluna_10": "FECH_FISICO"
    },
    "1320": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_BICO",
        "Coluna_3": "NR_INTERV",
        "Coluna_4": "MOT_INTERV",
        "Coluna_5": "NOM_INTERV",
        "Coluna_6": "CNPJ_INTERV",
        "Coluna_7": "CPF_INTERV",
        "Coluna_8": "VAL_FECHA",
        "Coluna_9": "VAL_ABERT",
        "Coluna_10": "VOL_AFERI",
        "Coluna_11": "VOL_VENDAS"
    },
    "1350": {
        "Coluna_1": "REG",
        "Coluna_2": "SERIE",
        "Coluna_3": "FABRICANTE",
        "Coluna_4": "MODELO",
        "Coluna_5": "TIPO_MEDICAO"
    },
    "1370": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_BICO",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "NUM_TANQUE"
    },
    "1390": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PROD"
    },
    "1391": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_REGISTRO",
        "Coluna_3": "QTD_MOID",
        "Coluna_4": "ESTQ_INI",
        "Coluna_5": "QTD_PRODUZ",
        "Coluna_6": "ENT_ANID_HID",
        "Coluna_7": "OUTR_ENTR",
        "Coluna_8": "PERDA",
        "Coluna_9": "CONS",
        "Coluna_10": "SAI_ANI_HID",
        "Coluna_11": "SA\u00cdDAS",
        "Coluna_12": "ESTQ_FIN",
        "Coluna_13": "ESTQ_INI_MEL",
        "Coluna_14": "PROD_DIA_MEL",
        "Coluna_15": "UTIL_MEL",
        "Coluna_16": "PROD_ALC_MEL",
        "Coluna_17": "OBS",
        "Coluna_18": "COD_ITEM",
        "Coluna_19": "TP_RESIDUO",
        "Coluna_20": "QTD_RESIDUO",
        "Coluna_21": "QTD_RESIDUO_ DDG",
        "Coluna_22": "QTD_RESIDUO_ WDG",
        "Coluna_23": "QTD_RESIDUO_ CANA"
    },
    "1400": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM_IPM",
        "Coluna_3": "MUN",
        "Coluna_4": "VALOR"
    },
    "1500": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_OPER",
        "Coluna_3": "IND_EMIT",
        "Coluna_4": "COD_PART",
        "Coluna_5": "COD_MOD",
        "Coluna_6": "COD_SIT",
        "Coluna_7": "SER",
        "Coluna_8": "SUB",
        "Coluna_9": "COD_CONS",
        "Coluna_10": "NUM_DOC",
        "Coluna_11": "DT_DOC",
        "Coluna_12": "DT_E_S",
        "Coluna_13": "VL_DOC",
        "Coluna_14": "VL_DESC",
        "Coluna_15": "VL_FORN",
        "Coluna_16": "VL_SERV_NT",
        "Coluna_17": "VL_TERC",
        "Coluna_18": "VL_DA",
        "Coluna_19": "VL_BC_ICMS",
        "Coluna_20": "VL_ICMS",
        "Coluna_21": "VL_BC_ICMS_ST",
        "Coluna_22": "VL_ICMS_ST",
        "Coluna_23": "COD_INF",
        "Coluna_24": "VL_PIS",
        "Coluna_25": "VL_COFINS",
        "Coluna_26": "TP_LIGACAO",
        "Coluna_27": "COD_GRUPO_TENSAO"
    },
    "1510": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_ITEM",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "COD_CLASS",
        "Coluna_5": "QTD",
        "Coluna_6": "UNID",
        "Coluna_7": "VL_ITEM",
        "Coluna_8": "VL_DESC",
        "Coluna_9": "CST_ICMS",
        "Coluna_10": "CFOP",
        "Coluna_11": "VL_BC_ICMS",
        "Coluna_12": "ALIQ_ICMS",
        "Coluna_13": "VL_ICMS",
        "Coluna_14": "VL_BC_ICMS_ST",
        "Coluna_15": "ALIQ_ST",
        "Coluna_16": "VL_ICMS_ST",
        "Coluna_17": "IND_REC",
        "Coluna_18": "COD_PART",
        "Coluna_19": "VL_PIS",
        "Coluna_20": "VL_COFINS",
        "Coluna_21": "COD_CTA"
    },
    "1600": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PART",
        "Coluna_3": "TOT_CREDITO",
        "Coluna_4": "TOT_DEBITO"
    },
    "1601": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PART_IP",
        "Coluna_3": "COD_PART_IT",
        "Coluna_4": "TOT_VS",
        "Coluna_5": "TOT_ISS",
        "Coluna_6": "TOT_OUTROS"
    },
    "1700": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_DISP",
        "Coluna_3": "COD_MOD",
        "Coluna_4": "SER",
        "Coluna_5": "SUB",
        "Coluna_6": "NUM_DOC_INI",
        "Coluna_7": "NUM_DOC_FIN",
        "Coluna_8": "NUM_AUT"
    },
    "1710": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_DOC_INI",
        "Coluna_3": "NUM_DOC_FIN"
    },
    "1800": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_CARGA",
        "Coluna_3": "VL_PASS",
        "Coluna_4": "VL_FAT",
        "Coluna_5": "IND_RAT",
        "Coluna_6": "VL_ICMS_ANT",
        "Coluna_7": "VL_BC_ICMS",
        "Coluna_8": "VL_ICMS_APUR",
        "Coluna_9": "VL_BC_ICMS_APUR",
        "Coluna_10": "VL_DIF"
    },
    "1900": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_APUR_ICMS",
        "Coluna_3": "DESCR_COMPL_OUT_APUR"
    },
    "1910": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_INI",
        "Coluna_3": "DT_FIN"
    },
    "1920": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_TOT_TRANSF_DEBITOS_OA",
        "Coluna_3": "VL_TOT_AJ_DEBITOS_OA",
        "Coluna_4": "VL_ESTORNOS_CRED_OA",
        "Coluna_5": "VL_TOT_TRANSF_CREDITOS_OA",
        "Coluna_6": "VL_TOT_AJ_CREDITOS_OA",
        "Coluna_7": "VL_ESTORNOS_DEB_OA",
        "Coluna_8": "VL_SLD_CREDOR_ANT_OA",
        "Coluna_9": "VL_SLD_APURADO_OA",
        "Coluna_10": "VL_TOT_DED",
        "Coluna_11": "VL_ICMS_RECOLHER_OA",
        "Coluna_12": "VL_SLD_CREDOR_TRANSP_OA",
        "Coluna_13": "DEB_ESP_OA"
    },
    "1921": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_AJ_APUR",
        "Coluna_3": "DESCR_COMPL_AJ",
        "Coluna_4": "VL_AJ_APUR"
    },
    "1922": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_DA",
        "Coluna_3": "NUM_PROC",
        "Coluna_4": "IND_PROC",
        "Coluna_5": "PROC",
        "Coluna_6": "TXT_COMPL"
    },
    "1923": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PART",
        "Coluna_3": "COD_MOD",
        "Coluna_4": "SER",
        "Coluna_5": "SUB",
        "Coluna_6": "NUM_DOC",
        "Coluna_7": "DT_DOC",
        "Coluna_8": "COD_ITEM",
        "Coluna_9": "VL_AJ_ITEM"
    },
    "1925": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_INF_ADIC",
        "Coluna_3": "VL_INF_ADIC",
        "Coluna_4": "DESCR_COMPL_AJ"
    },
    "1926": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_OR",
        "Coluna_3": "VL_OR",
        "Coluna_4": "DT_VCTO",
        "Coluna_5": "COD_REC",
        "Coluna_6": "NUM_PROC",
        "Coluna_7": "IND_PROC",
        "Coluna_8": "PROC",
        "Coluna_9": "TXT_COMPL",
        "Coluna_10": "MES_REF*"
    },
    "1960": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_AP",
        "Coluna_3": "G1_01",
        "Coluna_4": "G1_02",
        "Coluna_5": "G1_03",
        "Coluna_6": "G1_04",
        "Coluna_7": "G1_05",
        "Coluna_8": "G1_06",
        "Coluna_9": "G1_07",
        "Coluna_10": "G1_08",
        "Coluna_11": "G1_09",
        "Coluna_12": "G1_10",
        "Coluna_13": "G1_11"
    },
    "1970": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_AP",
        "Coluna_3": "G3_01",
        "Coluna_4": "G3_02",
        "Coluna_5": "G3_03",
        "Coluna_6": "G3_04",
        "Coluna_7": "G3_05",
        "Coluna_8": "G3_06",
        "Coluna_9": "G3_07",
        "Coluna_10": "G3_T",
        "Coluna_11": "G3_08",
        "Coluna_12": "G3_09"
    },
    "1975": {
        "Coluna_1": "REG",
        "Coluna_2": "ALIQ_IMP_BASE",
        "Coluna_3": "G3_10",
        "Coluna_4": "G3_11",
        "Coluna_5": "G3_12"
    },
    "1980": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_AP",
        "Coluna_3": "G4_01",
        "Coluna_4": "G4_02",
        "Coluna_5": "G4_03",
        "Coluna_6": "G4_04",
        "Coluna_7": "G4_05",
        "Coluna_8": "G4_06",
        "Coluna_9": "G4_07",
        "Coluna_10": "G4_08",
        "Coluna_11": "G4_09",
        "Coluna_12": "G4_10",
        "Coluna_13": "G4_11",
        "Coluna_14": "G4_12"
    },
    "1990": {
        "Coluna_1": "REG",
        "Coluna_2": "QTD_LIN_1"
    },
    "9001": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_MOV"
    },
    "9900": {
        "Coluna_1": "REG",
        "Coluna_2": "REG_BLC",
        "Coluna_3": "QTD_REG_BLC"
    },
    "9990": {
        "Coluna_1": "REG"
    },
    "9999": {
        "Coluna_1": "REG",
        "Coluna_2": "QTD_LIN"
    },
    "B001": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_DAD"
    },
    "B020": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_OPER",
        "Coluna_3": "IND_EMIT",
        "Coluna_4": "COD_PART",
        "Coluna_5": "COD_MOD",
        "Coluna_6": "COD_SIT",
        "Coluna_7": "SER",
        "Coluna_8": "NUM_DOC",
        "Coluna_9": "CHV_NFE",
        "Coluna_10": "DT_DOC",
        "Coluna_11": "COD_MUN_SE RV",
        "Coluna_12": "VL_CONT",
        "Coluna_13": "VL_MAT_TER C",
        "Coluna_14": "VL_SUB",
        "Coluna_15": "VL_ISNT_ISS",
        "Coluna_16": "VL_DED_BC",
        "Coluna_17": "VL_BC_ISS",
        "Coluna_18": "VL_BC_ISS_RT",
        "Coluna_19": "VL_ISS_RT",
        "Coluna_20": "VL_ ISS",
        "Coluna_21": "COD_INF_OBS"
    },
    "B025": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_CONT_P",
        "Coluna_3": "VL_BC_ISS_P",
        "Coluna_4": "ALIQ_ISS",
        "Coluna_5": "VL_ISS_P",
        "Coluna_6": "VL_ISNT_ISS_P",
        "Coluna_7": "COD_SERV"
    },
    "B030": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "SER",
        "Coluna_4": "NUM_DOC_INI",
        "Coluna_5": "NUM_DOC_FIN",
        "Coluna_6": "DT_DOC",
        "Coluna_7": "QTD_CANC",
        "Coluna_8": "VL_CONT",
        "Coluna_9": "VL_ISNT_ISS",
        "Coluna_10": "VL_BC_ISS",
        "Coluna_11": "VL_ ISS",
        "Coluna_12": "COD_INF_OBS"
    },
    "B035": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_CONT_P",
        "Coluna_3": "VL_BC_ISS_P",
        "Coluna_4": "ALIQ_ISS",
        "Coluna_5": "VL_ISS_P",
        "Coluna_6": "VL_ISNT_ISS_P",
        "Coluna_7": "COD_SERV"
    },
    "B350": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_CTD",
        "Coluna_3": "CTA_ISS",
        "Coluna_4": "CTA_COSIF",
        "Coluna_5": "QTD_OCOR",
        "Coluna_6": "COD_SERV",
        "Coluna_7": "VL_CONT",
        "Coluna_8": "VL_BC_ISS",
        "Coluna_9": "ALIQ_ISS",
        "Coluna_10": "VL_ISS",
        "Coluna_11": "COD_INF_OBS"
    },
    "B420": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_CONT",
        "Coluna_3": "VL_BC_ISS",
        "Coluna_4": "ALIQ_ISS",
        "Coluna_5": "VL_ISNT_ISS",
        "Coluna_6": "VL_ISS",
        "Coluna_7": "COD_SERV"
    },
    "B440": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_OPER",
        "Coluna_3": "COD_PART",
        "Coluna_4": "VL_CONT_RT",
        "Coluna_5": "VL_BC_ISS_R T",
        "Coluna_6": "VL_ISS_RT"
    },
    "B460": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_DED",
        "Coluna_3": "VL_DED",
        "Coluna_4": "NUM_PROC",
        "Coluna_5": "IND_PROC",
        "Coluna_6": "PROC",
        "Coluna_7": "COD_INF_OBS",
        "Coluna_8": "IND_OBR"
    },
    "B470": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_CONT",
        "Coluna_3": "VL_MAT_TERC",
        "Coluna_4": "VL_MAT_PROP",
        "Coluna_5": "VL_SUB",
        "Coluna_6": "VL_ISNT",
        "Coluna_7": "VL_DED_BC",
        "Coluna_8": "VL_BC_ISS",
        "Coluna_9": "VL_BC_ISS_RT",
        "Coluna_10": "VL_ ISS",
        "Coluna_11": "VL_ISS_RT",
        "Coluna_12": "VL_DED",
        "Coluna_13": "VL_ ISS_REC",
        "Coluna_14": "VL_ ISS_ST",
        "Coluna_15": "VL_ISS_REC_UNI"
    },
    "B500": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_REC",
        "Coluna_3": "QTD_PROF",
        "Coluna_4": "VL_OR"
    },
    "B510": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_PROF",
        "Coluna_3": "IND_ESC",
        "Coluna_4": "IND_SOC",
        "Coluna_5": "CPF",
        "Coluna_6": "NOME"
    },
    "B990": {
        "Coluna_1": "REG",
        "Coluna_2": "QTD_LIN_B"
    },
    "C001": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_MOV"
    },
    "C100": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_OPER",
        "Coluna_3": "IND_EMIT",
        "Coluna_4": "COD_PART",
        "Coluna_5": "COD_MOD",
        "Coluna_6": "COD_SIT",
        "Coluna_7": "SER",
        "Coluna_8": "NUM_DOC",
        "Coluna_9": "CHV_NFE",
        "Coluna_10": "DT_DOC",
        "Coluna_11": "DT_E_S",
        "Coluna_12": "VL_DOC",
        "Coluna_13": "IND_PGTO",
        "Coluna_14": "VL_DESC",
        "Coluna_15": "VL_ABAT_NT",
        "Coluna_16": "VL_MERC",
        "Coluna_17": "IND_FRT",
        "Coluna_18": "VL_FRT",
        "Coluna_19": "VL_SEG",
        "Coluna_20": "VL_OUT_DA",
        "Coluna_21": "VL_BC_ICMS",
        "Coluna_22": "VL_ICMS",
        "Coluna_23": "VL_BC_ICMS_ST",
        "Coluna_24": "VL_ICMS_ST",
        "Coluna_25": "VL_IPI",
        "Coluna_26": "VL_PIS",
        "Coluna_27": "VL_COFINS",
        "Coluna_28": "VL_PIS_ST",
        "Coluna_29": "VL_COFINS_ST"
    },
    "C101": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_FCP_UF_DEST",
        "Coluna_3": "VL_ICMS_UF_DEST",
        "Coluna_4": "VL_ICMS_UF_REM"
    },
    "C105": {
        "Coluna_1": "REG",
        "Coluna_2": "OPER",
        "Coluna_3": "UF"
    },
    "C110": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_INF",
        "Coluna_3": "TXT_COMPL"
    },
    "C111": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_PROC",
        "Coluna_3": "IND_PROC"
    },
    "C112": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_DA",
        "Coluna_3": "UF",
        "Coluna_4": "NUM_DA",
        "Coluna_5": "COD_AUT",
        "Coluna_6": "VL_DA",
        "Coluna_7": "DT_VCTO",
        "Coluna_8": "DT_PGTO"
    },
    "C113": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_OPER",
        "Coluna_3": "IND_EMIT",
        "Coluna_4": "COD_PART",
        "Coluna_5": "COD_MOD",
        "Coluna_6": "SER",
        "Coluna_7": "SUB",
        "Coluna_8": "NUM_DOC",
        "Coluna_9": "DT_DOC",
        "Coluna_10": "CHV_DOCe"
    },
    "C114": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "ECF_FAB",
        "Coluna_4": "ECF_CX",
        "Coluna_5": "NUM_DOC",
        "Coluna_6": "DT_DOC"
    },
    "C115": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_CARGA",
        "Coluna_3": "CNPJ_COL",
        "Coluna_4": "IE_COL",
        "Coluna_5": "CPF_COL",
        "Coluna_6": "COD_MUN_COL",
        "Coluna_7": "CNPJ_ENTG",
        "Coluna_8": "IE_ENTG",
        "Coluna_9": "CPF_ENTG",
        "Coluna_10": "COD_MUN_ENT G"
    },
    "C116": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "NR_SAT",
        "Coluna_4": "CHV_CFE",
        "Coluna_5": "NUM_CFE",
        "Coluna_6": "DT_DOC"
    },
    "C120": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_DOC_IMP",
        "Coluna_3": "NUM_DOC_IMP",
        "Coluna_4": "PIS_IMP",
        "Coluna_5": "COFINS IMP",
        "Coluna_6": "NUM_ACDRAW"
    },
    "C130": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_SERV_NT",
        "Coluna_3": "VL_BC_ISSQN",
        "Coluna_4": "VL_ISSQN",
        "Coluna_5": "VL_BC_IRRF",
        "Coluna_6": "VL_ IRRF",
        "Coluna_7": "VL_BC_PREV",
        "Coluna_8": "VL_ PREV"
    },
    "C140": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_EMIT",
        "Coluna_3": "IND_TIT",
        "Coluna_4": "DESC_TIT",
        "Coluna_5": "NUM_TIT",
        "Coluna_6": "QTD_PARC",
        "Coluna_7": "VL_TIT"
    },
    "C141": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_PARC",
        "Coluna_3": "DT_VCTO",
        "Coluna_4": "VL_PARC"
    },
    "C160": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PART",
        "Coluna_3": "VEIC_ID",
        "Coluna_4": "QTD_VOL",
        "Coluna_5": "PESO_BRT",
        "Coluna_6": "PESO_LIQ",
        "Coluna_7": "UF_ID"
    },
    "C165": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PART",
        "Coluna_3": "VEIC_ID",
        "Coluna_4": "COD_AUT",
        "Coluna_5": "NR_PASSE",
        "Coluna_6": "HORA",
        "Coluna_7": "TEMPER",
        "Coluna_8": "QTD_VOL",
        "Coluna_9": "PESO_BRT",
        "Coluna_10": "PESO_LIQ",
        "Coluna_11": "NOM_MOT",
        "Coluna_12": "CPF",
        "Coluna_13": "UF_ID"
    },
    "C170": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_ITEM",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "DESCR_COMPL",
        "Coluna_5": "QTD",
        "Coluna_6": "UNID",
        "Coluna_7": "VL_ITEM",
        "Coluna_8": "VL_DESC",
        "Coluna_9": "IND_MOV",
        "Coluna_10": "CST_ICMS",
        "Coluna_11": "CFOP",
        "Coluna_12": "COD_NAT",
        "Coluna_13": "VL_BC_ICMS",
        "Coluna_14": "ALIQ_ICMS",
        "Coluna_15": "VL_ICMS",
        "Coluna_16": "VL_BC_ICMS_ST",
        "Coluna_17": "ALIQ_ST",
        "Coluna_18": "VL_ICMS_ST",
        "Coluna_19": "IND_APUR",
        "Coluna_20": "CST_IPI",
        "Coluna_21": "COD_ENQ",
        "Coluna_22": "VL_BC_IPI",
        "Coluna_23": "ALIQ_IPI",
        "Coluna_24": "VL_IPI",
        "Coluna_25": "CST_PIS",
        "Coluna_26": "VL_BC_PIS",
        "Coluna_27": "ALIQ_PIS",
        "Coluna_28": "QUANT_BC_PIS",
        "Coluna_29": "ALIQ_PIS",
        "Coluna_30": "VL_PIS",
        "Coluna_31": "CST_COFINS",
        "Coluna_32": "VL_BC_COFINS",
        "Coluna_33": "ALIQ_COFINS",
        "Coluna_34": "QUANT_BC_COF INS",
        "Coluna_35": "ALIQ_COFINS",
        "Coluna_36": "VL_COFINS",
        "Coluna_37": "COD_CTA",
        "Coluna_38": "VL_ABAT_NT"
    },
    "C171": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_TANQUE",
        "Coluna_3": "QTDE"
    },
    "C172": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_BC_ISSQN",
        "Coluna_3": "ALIQ_ISSQN",
        "Coluna_4": "VL_ISSQN"
    },
    "C173": {
        "Coluna_1": "REG",
        "Coluna_2": "LOTE_MED",
        "Coluna_3": "QTD_ITEM",
        "Coluna_4": "DT_FAB",
        "Coluna_5": "DT_VAL",
        "Coluna_6": "IND_MED",
        "Coluna_7": "TP_PROD",
        "Coluna_8": "VL_TAB_MAX"
    },
    "C174": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_ARM",
        "Coluna_3": "NUM_ARM",
        "Coluna_4": "DESCR_COMPL"
    },
    "C175": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_VEIC_OPER",
        "Coluna_3": "CNPJ",
        "Coluna_4": "UF",
        "Coluna_5": "CHASSI_VEIC"
    },
    "C176": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD_ULT_E",
        "Coluna_3": "NUM_DOC_ULT_E",
        "Coluna_4": "SER_ULT_E",
        "Coluna_5": "DT_ULT_E",
        "Coluna_6": "COD_PART_ULT_E",
        "Coluna_7": "QUANT_ULT_E",
        "Coluna_8": "VL_UNIT_ULT_E",
        "Coluna_9": "VL_UNIT_BC_ST",
        "Coluna_10": "CHAVE_NFE_ULT_ E",
        "Coluna_11": "NUM_ITEM_ULT_E",
        "Coluna_12": "VL_UNIT_BC_ICMS _ULT_E",
        "Coluna_13": "ALIQ_ICMS_ULT_E",
        "Coluna_14": "VL_UNIT_LIMITE_B C_ICMS_ULT_E",
        "Coluna_15": "VL_UNIT_ICMS_UL T_E",
        "Coluna_16": "ALIQ_ST_ULT_E",
        "Coluna_17": "VL_UNIT_RES",
        "Coluna_18": "COD_RESP_RET",
        "Coluna_19": "COD_MOT_RES",
        "Coluna_20": "CHAVE_NFE_RET",
        "Coluna_21": "COD_PART_NFE_R ET",
        "Coluna_22": "SER_NFE_RET",
        "Coluna_23": "NUM_NFE_RET",
        "Coluna_24": "ITEM_NFE_RET",
        "Coluna_25": "COD_DA",
        "Coluna_26": "NUM_DA",
        "Coluna_27": "VL_UNIT_RES_FCP _ST"
    },
    "C177": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_SELO_IPI",
        "Coluna_3": "COD_INF_ITE M",
        "Coluna_4": "QT_SELO_IPI"
    },
    "C178": {
        "Coluna_1": "REG",
        "Coluna_2": "CL_ENQ",
        "Coluna_3": "VL_UNID",
        "Coluna_4": "QUANT_PAD"
    },
    "C179": {
        "Coluna_1": "REG",
        "Coluna_2": "BC_ST_ORIG_DEST",
        "Coluna_3": "ICMS_ST_REP",
        "Coluna_4": "ICMS_ST_COMPL",
        "Coluna_5": "BC_RET",
        "Coluna_6": "ICMS_RET"
    },
    "C180": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_RESP_RET",
        "Coluna_3": "QUANT_CONV",
        "Coluna_4": "UNID",
        "Coluna_5": "VL_UNIT_CONV",
        "Coluna_6": "VL_UNIT_ICMS_OP_CONV",
        "Coluna_7": "VL_UNIT_BC_ICMS_ST _CONV",
        "Coluna_8": "VL_UNIT_ICMS_ST_CONV",
        "Coluna_9": "VL_UNIT_FCP_ST_CONV",
        "Coluna_10": "COD_DA",
        "Coluna_11": "NUM_DA"
    },
    "C181": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOT_REST_COMPL",
        "Coluna_3": "QUANT_CONV",
        "Coluna_4": "UNID",
        "Coluna_5": "COD_MOD_SAIDA",
        "Coluna_6": "SERIE_SAIDA",
        "Coluna_7": "ECF_FAB_SAIDA",
        "Coluna_8": "NUM_DOC_SAIDA",
        "Coluna_9": "CHV_DFE_SAIDA",
        "Coluna_10": "DT_DOC_SAIDA",
        "Coluna_11": "NUM_ITEM_SAIDA",
        "Coluna_12": "VL_UNIT_CONV_SAIDA",
        "Coluna_13": "VL_UNIT_ICMS_OP_EST OQUE_CONV_SAIDA",
        "Coluna_14": "VL_UNIT_ICMS_ST_EST OQUE_CONV_SAIDA",
        "Coluna_15": "VL_UNIT_FCP_ICMS_ST_ ESTOQUE_CONV_SAIDA",
        "Coluna_16": "VL_UNIT_ICMS_NA_OPE RACAO_CONV_SAIDA",
        "Coluna_17": "VL_UNIT_ICMS_OP_CON V_SAIDA",
        "Coluna_18": "VL_UNIT_ICMS_ST_CON V_REST",
        "Coluna_19": "VL_UNIT_FCP_ST_CONV _REST",
        "Coluna_20": "VL_UNIT_ICMS_ST_CON V_COMPL",
        "Coluna_21": "VL_UNIT_FCP_ST_CONV COMPL ^^^^^^"
    },
    "C185": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_ITEM",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "CST_ICMS",
        "Coluna_5": "CFOP",
        "Coluna_6": "COD_MOT_REST_COMPL",
        "Coluna_7": "QUANT_CONV",
        "Coluna_8": "UNID",
        "Coluna_9": "VL_UNIT_CONV",
        "Coluna_10": "VL_UNIT_ICMS_NA_OPER ACAO_CONV",
        "Coluna_11": "VL_UNIT_ICMS_OP_CONV",
        "Coluna_12": "VL_UNIT_ICMS_OP_ESTO QUE_CONV",
        "Coluna_13": "VL_UNIT_ICMS_ST_ESTO QUE_CONV",
        "Coluna_14": "VL_UNIT_FCP_ICMS_ST_E STOQUE_CONV",
        "Coluna_15": "VL_UNIT_ICMS_ST_CONV _REST",
        "Coluna_16": "VL_UNIT_FCP_ST_CONV_ REST",
        "Coluna_17": "VL_UNIT_ICMS_ST_CONV _COMPL",
        "Coluna_18": "VL_UNIT_FCP_ST_CONV_ COMPL"
    },
    "C186": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_ITEM",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "CST_ICMS",
        "Coluna_5": "CFOP",
        "Coluna_6": "COD_MOT_REST_COMPL",
        "Coluna_7": "QUANT_CONV",
        "Coluna_8": "UNID",
        "Coluna_9": "COD_MOD_ENTRADA",
        "Coluna_10": "SERIE_ENTRADA",
        "Coluna_11": "NUM_DOC_ENTRADA",
        "Coluna_12": "CHV_DFE_ENTRADA",
        "Coluna_13": "DT_DOC_ENTRADA",
        "Coluna_14": "NUM_ITEM_ENTRADA",
        "Coluna_15": "VL_UNIT_CONV_ENTRADA",
        "Coluna_16": "VL_UNIT_ICMS_OP_CONV_ ENTRADA",
        "Coluna_17": "VL_UNIT_BC_ICMS_ST _CONV_ENTRADA",
        "Coluna_18": "VL_UNIT_ICMS_ST_CONV_ ENTRADA",
        "Coluna_19": "VL_UNIT_FCP_ST_CONV_E NTRADA"
    },
    "C190": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_BC_ICMS_ ST",
        "Coluna_9": "VL_ICMS_ST",
        "Coluna_10": "VL_RED_BC",
        "Coluna_11": "VL_IPI",
        "Coluna_12": "COD_OBS"
    },
    "C195": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_OBS",
        "Coluna_3": "TXT_COMPL"
    },
    "C197": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_AJ",
        "Coluna_3": "DESCR_COMPL_AJ",
        "Coluna_4": "COD_ITEM",
        "Coluna_5": "VL_BC_ICMS",
        "Coluna_6": "ALIQ_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_OUTROS"
    },
    "C300": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "SER",
        "Coluna_4": "SUB",
        "Coluna_5": "NUM_DOC_INI",
        "Coluna_6": "NUM_DOC_FIN",
        "Coluna_7": "DT_DOC",
        "Coluna_8": "VL_DOC",
        "Coluna_9": "VL_PIS",
        "Coluna_10": "VL_COFINS",
        "Coluna_11": "COD_CTA"
    },
    "C310": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_DOC_CANC"
    },
    "C320": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_RED_BC",
        "Coluna_9": "COD_OBS"
    },
    "C321": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM",
        "Coluna_3": "QTD",
        "Coluna_4": "UNID",
        "Coluna_5": "VL_ITEM",
        "Coluna_6": "VL_DESC",
        "Coluna_7": "VL_BC_ICMS",
        "Coluna_8": "VL_ICMS",
        "Coluna_9": "VL_PIS",
        "Coluna_10": "VL_COFINS"
    },
    "C330": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOT_REST_COMPL",
        "Coluna_3": "QUANT_CONV",
        "Coluna_4": "UNID",
        "Coluna_5": "VL_UNIT_CONV",
        "Coluna_6": "VL_UNIT_ICMS_NA_OPER ACAO_CONV",
        "Coluna_7": "VL_UNIT_ICMS_OP_CON V",
        "Coluna_8": "VL_UNIT_ICMS_OP_ESTO QUE_CONV",
        "Coluna_9": "VL_UNIT_ICMS_ST_ESTO QUE_CONV",
        "Coluna_10": "VL_UNIT_FCP_ICMS_ST_ ESTOQUE_CONV",
        "Coluna_11": "VL_UNIT_ICMS_ST_CONV _REST",
        "Coluna_12": "VL_UNIT_FCP_ST_CONV_ REST",
        "Coluna_13": "VL_UNIT_ICMS_ST_CONV _COMPL",
        "Coluna_14": "VL_UNIT_FCP_ST_CONV_ COMPL"
    },
    "C350": {
        "Coluna_1": "REG",
        "Coluna_2": "SER",
        "Coluna_3": "SUB_SER",
        "Coluna_4": "NUM_DOC",
        "Coluna_5": "DT_DOC",
        "Coluna_6": "CNPJ_CPF",
        "Coluna_7": "VL_MERC",
        "Coluna_8": "VL_DOC",
        "Coluna_9": "VL_DESC",
        "Coluna_10": "VL_PIS",
        "Coluna_11": "VL_COFINS",
        "Coluna_12": "COD_CTA"
    },
    "C370": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_ITEM",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "QTD",
        "Coluna_5": "UNID",
        "Coluna_6": "VL_ITEM",
        "Coluna_7": "VL_DESC"
    },
    "C380": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOT_REST_CO MPL",
        "Coluna_3": "QUANT_CONV",
        "Coluna_4": "UNID",
        "Coluna_5": "VL_UNIT_CONV",
        "Coluna_6": "VL_UNIT_ICMS_NA_O PERACAO_CONV",
        "Coluna_7": "VL_UNIT_ICMS_OP_C ONV",
        "Coluna_8": "VL_UNIT_ICMS_OP_E STOQUE_CONV",
        "Coluna_9": "VL_UNIT_ICMS_ST_ES TOQUE_CONV",
        "Coluna_10": "VL_UNIT_FCP_ICMS_S T_ESTOQUE_CONV",
        "Coluna_11": "VL_UNIT_ICMS_ST_C ONV_REST",
        "Coluna_12": "VL_UNIT_FCP_ST_CO NV_REST",
        "Coluna_13": "VL_UNIT_ICMS_ST_C ONV_COMPL",
        "Coluna_14": "VL_UNIT_FCP_ST_CO NV_COMPL",
        "Coluna_15": "CST_ICMS",
        "Coluna_16": "CFOP"
    },
    "C390": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_RED_BC",
        "Coluna_9": "COD_OBS"
    },
    "C400": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "ECF_MOD",
        "Coluna_4": "ECF_FAB",
        "Coluna_5": "ECF_CX"
    },
    "C405": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_DOC",
        "Coluna_3": "CRO",
        "Coluna_4": "CRZ",
        "Coluna_5": "NUM_COO_FI N",
        "Coluna_6": "GT_FIN",
        "Coluna_7": "VL_BRT"
    },
    "C410": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_PIS",
        "Coluna_3": "VL_COFINS"
    },
    "C420": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_TOT_PAR",
        "Coluna_3": "VLR_ACUM_TOT",
        "Coluna_4": "NR_TOT",
        "Coluna_5": "DESCR_NR_TOT"
    },
    "C425": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM",
        "Coluna_3": "QTD",
        "Coluna_4": "UNID",
        "Coluna_5": "VL_ITEM",
        "Coluna_6": "VL_PIS",
        "Coluna_7": "VL_COFINS"
    },
    "C430": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOT_REST_COMP L",
        "Coluna_3": "QUANT_CONV",
        "Coluna_4": "UNID",
        "Coluna_5": "VL_UNIT_CONV",
        "Coluna_6": "VL_UNIT_ICMS_NA_OPE RACAO_CONV",
        "Coluna_7": "VL_UNIT_ICMS_OP_CO NV",
        "Coluna_8": "VL_UNIT_ICMS_OP_EST OQUE_CONV",
        "Coluna_9": "VL_UNIT_ICMS_ST_EST OQUE_CONV",
        "Coluna_10": "VL_UNIT_FCP_ICMS_ST _ESTOQUE_CONV",
        "Coluna_11": "VL_UNIT_ICMS_ST_CON V_REST",
        "Coluna_12": "VL_UNIT_FCP_ST_CONV _REST",
        "Coluna_13": "VL_UNIT_ICMS_ST_CON V_COMPL",
        "Coluna_14": "VL_UNIT_FCP_ST_CONV _COMPL",
        "Coluna_15": "CST_ICMS",
        "Coluna_16": "CFOP"
    },
    "C460": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "COD_SIT",
        "Coluna_4": "NUM_DOC",
        "Coluna_5": "DT_DOC",
        "Coluna_6": "VL_DOC",
        "Coluna_7": "VL_PIS",
        "Coluna_8": "VL_COFINS",
        "Coluna_9": "CPF_CNPJ",
        "Coluna_10": "NOM_ADQ"
    },
    "C465": {
        "Coluna_1": "REG",
        "Coluna_2": "CHV_CFE",
        "Coluna_3": "NUM_CCF"
    },
    "C470": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM",
        "Coluna_3": "QTD",
        "Coluna_4": "QTD_CANC",
        "Coluna_5": "UNID",
        "Coluna_6": "VL_ITEM",
        "Coluna_7": "CST_ICMS",
        "Coluna_8": "CFOP",
        "Coluna_9": "ALIQ_ICMS",
        "Coluna_10": "VL_PIS",
        "Coluna_11": "VL_COFINS"
    },
    "C480": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOT_REST_C OMPL",
        "Coluna_3": "QUANT_CONV",
        "Coluna_4": "UNID",
        "Coluna_5": "VL_UNIT_CONV",
        "Coluna_6": "VL_UNIT_ICMS_NA _OPERACAO_CONV",
        "Coluna_7": "VL_UNIT_ICMS_OP _CONV",
        "Coluna_8": "VL_UNIT_ICMS_OP _ESTOQUE_CONV",
        "Coluna_9": "VL_UNIT_ICMS_ST_ ESTOQUE_CONV",
        "Coluna_10": "VL_UNIT_FCP_ICM S_ST_ESTOQUE_CO NV",
        "Coluna_11": "VL_UNIT_ICMS_ST_ CONV_REST",
        "Coluna_12": "VL_UNIT_FCP_ST_C ONV_REST",
        "Coluna_13": "VL_UNIT_ICMS_ST_ CONV_COMPL",
        "Coluna_14": "VL_UNIT_FCP_ST_C ONV_COMPL",
        "Coluna_15": "CST_ICMS",
        "Coluna_16": "CFOP"
    },
    "C490": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "COD_OBS"
    },
    "C495": {
        "Coluna_1": "REG",
        "Coluna_2": "ALIQ_ICMS",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "QTD",
        "Coluna_5": "QTD_CANC",
        "Coluna_6": "UNID",
        "Coluna_7": "VL_ITEM",
        "Coluna_8": "VL_DESC",
        "Coluna_9": "VL_CANC",
        "Coluna_10": "VL_ACMO",
        "Coluna_11": "VL_BC_ICMS",
        "Coluna_12": "VL_ICMS",
        "Coluna_13": "VL_ISEN",
        "Coluna_14": "VL_NT",
        "Coluna_15": "VL_ICMS_ST"
    },
    "C500": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_OPER",
        "Coluna_3": "IND_EMIT",
        "Coluna_4": "COD_PART",
        "Coluna_5": "COD_MOD",
        "Coluna_6": "COD_SIT",
        "Coluna_7": "SER",
        "Coluna_8": "SUB",
        "Coluna_9": "COD_CONS",
        "Coluna_10": "NUM_DOC",
        "Coluna_11": "DT_DOC",
        "Coluna_12": "DT_E_S",
        "Coluna_13": "VL_DOC",
        "Coluna_14": "VL_DESC",
        "Coluna_15": "VL_FORN",
        "Coluna_16": "VL_SERV_NT",
        "Coluna_17": "VL_TERC",
        "Coluna_18": "VL_DA",
        "Coluna_19": "VL_BC_ICMS",
        "Coluna_20": "VL_ICMS",
        "Coluna_21": "VL_BC_ICMS_ST",
        "Coluna_22": "VL_ICMS_ST",
        "Coluna_23": "COD_INF",
        "Coluna_24": "VL_PIS",
        "Coluna_25": "VL_COFINS",
        "Coluna_26": "TP LIGACAO",
        "Coluna_27": "COD_GRUPO_TENSAO",
        "Coluna_28": "CHV_DOCe",
        "Coluna_29": "FIN_DOCe",
        "Coluna_30": "CHV_DOCe_REF",
        "Coluna_31": "IND_DEST",
        "Coluna_32": "COD_MUN_DEST",
        "Coluna_33": "COD_CTA",
        "Coluna_34": "COD_MOD_DOC_REF",
        "Coluna_35": "HASH_DOC_REF",
        "Coluna_36": "SER_DOC_REF",
        "Coluna_37": "NUM_DOC_REF",
        "Coluna_38": "MES_DOC_REF",
        "Coluna_39": "ENER_INJET",
        "Coluna_40": "OUTRAS_DED"
    },
    "C510": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_ITEM",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "COD_CLASS",
        "Coluna_5": "QTD",
        "Coluna_6": "UNID",
        "Coluna_7": "VL_ITEM",
        "Coluna_8": "VL_DESC",
        "Coluna_9": "CST_ICMS",
        "Coluna_10": "CFOP",
        "Coluna_11": "VL_BC_ICMS",
        "Coluna_12": "ALIQ_ICMS",
        "Coluna_13": "VL_ICMS",
        "Coluna_14": "VL_BC_ICMS_S T",
        "Coluna_15": "ALIQ_ST",
        "Coluna_16": "VL_ICMS_ST",
        "Coluna_17": "IND_REC",
        "Coluna_18": "COD_PART",
        "Coluna_19": "VL_PIS",
        "Coluna_20": "VL_COFINS",
        "Coluna_21": "COD_CTA"
    },
    "C590": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_BC_ICMS_ST",
        "Coluna_9": "VL_ICMS_ST",
        "Coluna_10": "VL_RED_BC",
        "Coluna_11": "COD_OBS"
    },
    "C591": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_FCP_OP",
        "Coluna_3": "VL_FCP_ST"
    },
    "C595": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_OBS",
        "Coluna_3": "TXT_COMPL"
    },
    "C597": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_AJ",
        "Coluna_3": "DESCR_COMPL_AJ",
        "Coluna_4": "COD_ITEM",
        "Coluna_5": "VL_BC_ICMS",
        "Coluna_6": "ALIQ_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_OUTROS"
    },
    "C600": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "COD_MUN",
        "Coluna_4": "SER",
        "Coluna_5": "SUB",
        "Coluna_6": "COD_CONS",
        "Coluna_7": "QTD_CONS",
        "Coluna_8": "QTD_CANC",
        "Coluna_9": "DT_DOC",
        "Coluna_10": "VL_DOC",
        "Coluna_11": "VL_DESC",
        "Coluna_12": "CONS",
        "Coluna_13": "VL_FORN",
        "Coluna_14": "VL_SERV_NT",
        "Coluna_15": "VL_TERC",
        "Coluna_16": "VL_DA",
        "Coluna_17": "VL_BC_ICMS",
        "Coluna_18": "VL_ICMS",
        "Coluna_19": "VL_BC_ICMS_ST",
        "Coluna_20": "VL_ICMS_ST",
        "Coluna_21": "VL_PIS",
        "Coluna_22": "VL_COFINS"
    },
    "C601": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_DOC_CANC"
    },
    "C610": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_CLASS",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "QTD",
        "Coluna_5": "UNID",
        "Coluna_6": "VL_ITEM",
        "Coluna_7": "VL_DESC",
        "Coluna_8": "CST_ICMS",
        "Coluna_9": "CFOP",
        "Coluna_10": "ALIQ_ICMS",
        "Coluna_11": "VL_BC_ICMS",
        "Coluna_12": "VL_ICMS",
        "Coluna_13": "VL_BC_ICMS_ST",
        "Coluna_14": "VL_ICMS_ST",
        "Coluna_15": "VL_PIS",
        "Coluna_16": "VL_COFINS",
        "Coluna_17": "COD_CTA"
    },
    "C690": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_RED_BC",
        "Coluna_9": "VL_BC_ICMS_ST",
        "Coluna_10": "VL_ICMS_ST",
        "Coluna_11": "COD_OBS"
    },
    "C700": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "SER",
        "Coluna_4": "NRO_ORD_INI",
        "Coluna_5": "NRO_ORD_FIN",
        "Coluna_6": "DT_DOC_INI",
        "Coluna_7": "DT_DOC_FIN",
        "Coluna_8": "NOM_MEST",
        "Coluna_9": "CHV_COD_DIG"
    },
    "C790": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_BC_ICMS_ST",
        "Coluna_9": "VL_ICMS_ST",
        "Coluna_10": "VL_RED_BC",
        "Coluna_11": "COD_OBS"
    },
    "C791": {
        "Coluna_1": "REG",
        "Coluna_2": "UF",
        "Coluna_3": "VL_BC_ICMS_ST",
        "Coluna_4": "VL_ICMS_ST"
    },
    "C800": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "COD_SIT",
        "Coluna_4": "NUM_CFE",
        "Coluna_5": "DT_DOC",
        "Coluna_6": "VL_CFE",
        "Coluna_7": "VL_PIS",
        "Coluna_8": "VL_COFINS",
        "Coluna_9": "CNPJ_CPF",
        "Coluna_10": "NR_SAT",
        "Coluna_11": "CHV_CFE",
        "Coluna_12": "VL_DESC",
        "Coluna_13": "VL_MERC",
        "Coluna_14": "VL_OUT_DA",
        "Coluna_15": "VL_ICMS",
        "Coluna_16": "VL_PIS_ST",
        "Coluna_17": "VL_COFINS_ST"
    },
    "C810": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_ITEM",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "QTD",
        "Coluna_5": "UNID",
        "Coluna_6": "VL_ITEM",
        "Coluna_7": "CST_ICMS",
        "Coluna_8": "CFOP"
    },
    "C815": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOT_REST_COMPL",
        "Coluna_3": "QUANT_CONV",
        "Coluna_4": "UNID",
        "Coluna_5": "VL_UNIT_CONV",
        "Coluna_6": "VL_UNIT_ICMS_NA_OPE RACAO_CONV",
        "Coluna_7": "VL_UNIT_ICMS_OP_CON V",
        "Coluna_8": "VL_UNIT_ICMS_OP_EST OQUE_CONV",
        "Coluna_9": "VL_UNIT_ICMS_ST_ESTO QUE_CONV",
        "Coluna_10": "VL_UNIT_FCP_ICMS_ST_ ESTOQUE_CONV",
        "Coluna_11": "VL_UNIT_ICMS_ST_CON V_REST",
        "Coluna_12": "VL_UNIT_FCP_ST_CONV _REST",
        "Coluna_13": "VL_UNIT_ICMS_ST_CON V_COMPL",
        "Coluna_14": "VL_UNIT_FCP_ST_CONV _COMPL"
    },
    "C850": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "COD_OBS"
    },
    "C855": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_OBS",
        "Coluna_3": "TXT_COMPL"
    },
    "C857": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_AJ",
        "Coluna_3": "DESCR_COMPL_AJ",
        "Coluna_4": "COD_ITEM",
        "Coluna_5": "VL_BC_ICMS",
        "Coluna_6": "ALIQ_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_OUTROS"
    },
    "C860": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "NR_SAT",
        "Coluna_4": "DT_DOC",
        "Coluna_5": "DOC_INI",
        "Coluna_6": "DOC_FIM"
    },
    "C870": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM",
        "Coluna_3": "QTD",
        "Coluna_4": "UNID",
        "Coluna_5": "CST_ICMS",
        "Coluna_6": "CFOP"
    },
    "C880": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOT_REST_COMPL",
        "Coluna_3": "QUANT_CONV",
        "Coluna_4": "UNID",
        "Coluna_5": "VL_UNIT_CONV",
        "Coluna_6": "VL_UNIT_ICMS_NA_OPE RACAO_CONV",
        "Coluna_7": "VL_UNIT_ICMS_OP_CON V",
        "Coluna_8": "VL_UNIT_ICMS_OP_EST OQUE_CONV",
        "Coluna_9": "VL_UNIT_ICMS_ST_EST OQUE_CONV",
        "Coluna_10": "VL_UNIT_FCP_ICMS_ST_ ESTOQUE_CONV",
        "Coluna_11": "VL_UNIT_ICMS_ST_CON V_REST",
        "Coluna_12": "VL_UNIT_FCP_ST_CONV _REST",
        "Coluna_13": "VL_UNIT_ICMS_ST_CON V_COMPL",
        "Coluna_14": "VL_UNIT_FCP_ST_CONV COMPL _"
    },
    "C890": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "COD_OBS"
    },
    "C895": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_OBS",
        "Coluna_3": "TXT_COMPL"
    },
    "C897": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_AJ",
        "Coluna_3": "DESCR_COMPL_AJ",
        "Coluna_4": "COD_ITEM",
        "Coluna_5": "VL_BC_ICMS",
        "Coluna_6": "ALIQ_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_OUTROS"
    },
    "C990": {
        "Coluna_1": "REG",
        "Coluna_2": "QTD_LIN_C"
    },
    "D001": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_MOV"
    },
    "D100": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_OPER",
        "Coluna_3": "IND_EMIT",
        "Coluna_4": "COD_PART",
        "Coluna_5": "COD_MOD",
        "Coluna_6": "COD_SIT",
        "Coluna_7": "SER",
        "Coluna_8": "SUB",
        "Coluna_9": "NUM_DOC",
        "Coluna_10": "CHV_CTE",
        "Coluna_11": "DT_DOC",
        "Coluna_12": "DT_A_P",
        "Coluna_13": "TP_CT-e",
        "Coluna_14": "CHV_CTE_REF",
        "Coluna_15": "VL_DOC",
        "Coluna_16": "VL_DESC",
        "Coluna_17": "IND_FRT",
        "Coluna_18": "VL_SERV",
        "Coluna_19": "VL_BC_ICMS",
        "Coluna_20": "VL_ICMS",
        "Coluna_21": "VL_NT",
        "Coluna_22": "COD_INF",
        "Coluna_23": "COD_CTA",
        "Coluna_24": "COD_MUN_ORIG",
        "Coluna_25": "COD_MUN_DEST"
    },
    "D101": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_FCP_UF_DEST",
        "Coluna_3": "VL_ICMS_UF_DES T",
        "Coluna_4": "VL_ICMS_UF_REM"
    },
    "D110": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_ITEM",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "VL_SERV",
        "Coluna_5": "VL_OUT"
    },
    "D120": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MUN_ORIG",
        "Coluna_3": "COD_MUN_DEST",
        "Coluna_4": "VEIC_ID",
        "Coluna_5": "UF_ID"
    },
    "D130": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PART_CONSG",
        "Coluna_3": "COD_PART_RED",
        "Coluna_4": "IND_FRT_RED",
        "Coluna_5": "COD_MUN_ORIG",
        "Coluna_6": "COD_MUN_DEST",
        "Coluna_7": "VEIC_ID",
        "Coluna_8": "VL_LIQ_FRT",
        "Coluna_9": "VL_SEC_CAT",
        "Coluna_10": "VL_DESP",
        "Coluna_11": "VL_PEDG",
        "Coluna_12": "VL_OUT",
        "Coluna_13": "VL_FRT",
        "Coluna_14": "UF_ID"
    },
    "D140": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PART_CONSG",
        "Coluna_3": "COD_MUN_ORIG",
        "Coluna_4": "COD_MUN_DEST",
        "Coluna_5": "IND_VEIC",
        "Coluna_6": "VEIC_ID",
        "Coluna_7": "IND_NAV",
        "Coluna_8": "VIAGEM",
        "Coluna_9": "VL_FRT_LIQ",
        "Coluna_10": "VL_DESP_PORT",
        "Coluna_11": "VL_DESP_CAR_DE SC",
        "Coluna_12": "VL_OUT",
        "Coluna_13": "VL_FRT_BRT",
        "Coluna_14": "VL_FRT_MM"
    },
    "D150": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MUN_ORIG",
        "Coluna_3": "COD_MUN_DEST",
        "Coluna_4": "VEIC_ID",
        "Coluna_5": "VIAGEM",
        "Coluna_6": "IND_TFA",
        "Coluna_7": "VL_PESO_TX",
        "Coluna_8": "VL_TX_TERR",
        "Coluna_9": "VL_TX_RED",
        "Coluna_10": "VL_OUT",
        "Coluna_11": "VL_TX_ADV"
    },
    "D160": {
        "Coluna_1": "REG",
        "Coluna_2": "DESPACHO",
        "Coluna_3": "CNPJ_CPF_REM",
        "Coluna_4": "IE_REM",
        "Coluna_5": "COD_MUN_ORI",
        "Coluna_6": "CNPJ_CPF_DEST",
        "Coluna_7": "IE_DEST",
        "Coluna_8": "COD_MUN_DEST"
    },
    "D161": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_CARGA",
        "Coluna_3": "CNPJ_CPF_COL",
        "Coluna_4": "IE_COL",
        "Coluna_5": "COD_MUN_COL",
        "Coluna_6": "CNPJ_CPF_ENTG",
        "Coluna_7": "IE_ENTG",
        "Coluna_8": "COD_MUN_ENTG"
    },
    "D162": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "SER",
        "Coluna_4": "NUM_DOC",
        "Coluna_5": "DT_DOC",
        "Coluna_6": "VL_DOC",
        "Coluna_7": "VL_MERC",
        "Coluna_8": "QTD_VOL",
        "Coluna_9": "PESO_BRT",
        "Coluna_10": "PESO_LIQ"
    },
    "D170": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PART_CONSG",
        "Coluna_3": "COD_PART_RED",
        "Coluna_4": "COD_MUN_ORIG",
        "Coluna_5": "COD_MUN_DEST",
        "Coluna_6": "OTM",
        "Coluna_7": "IND_NAT_FRT",
        "Coluna_8": "VL_LIQ_FRT",
        "Coluna_9": "VL_GRIS",
        "Coluna_10": "VL_PDG",
        "Coluna_11": "VL_OUT",
        "Coluna_12": "VL_FRT",
        "Coluna_13": "VEIC_ID",
        "Coluna_14": "UF_ID"
    },
    "D180": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_SEQ",
        "Coluna_3": "IND_EMIT",
        "Coluna_4": "CNPJ_CPF_EMIT",
        "Coluna_5": "UF_EMIT",
        "Coluna_6": "IE_EMIT",
        "Coluna_7": "COD_MUN_ORIG",
        "Coluna_8": "CNPJ_CPF_TOM",
        "Coluna_9": "UF_TOM",
        "Coluna_10": "IE_TOM",
        "Coluna_11": "COD_MUN_DEST",
        "Coluna_12": "COD_MOD",
        "Coluna_13": "SER",
        "Coluna_14": "SUB",
        "Coluna_15": "NUM_DOC",
        "Coluna_16": "DT_DOC",
        "Coluna_17": "VL_DOC"
    },
    "D190": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_RED_BC",
        "Coluna_9": "COD_OBS"
    },
    "D195": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_OBS",
        "Coluna_3": "TXT_COMPL"
    },
    "D197": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_AJ",
        "Coluna_3": "DESCR_COMPL_AJ",
        "Coluna_4": "COD_ITEM",
        "Coluna_5": "VL_BC_ICMS",
        "Coluna_6": "ALIQ_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_OUTROS"
    },
    "D300": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "SER",
        "Coluna_4": "SUB",
        "Coluna_5": "NUM_DOC_INI",
        "Coluna_6": "NUM_DOC_FI N",
        "Coluna_7": "CST_ICMS",
        "Coluna_8": "CFOP",
        "Coluna_9": "ALIQ_ICMS",
        "Coluna_10": "DT_DOC",
        "Coluna_11": "VL_OPR",
        "Coluna_12": "VL_DESC",
        "Coluna_13": "VL_SERV",
        "Coluna_14": "VL_SEG",
        "Coluna_15": "VL_OUT DESP",
        "Coluna_16": "VL_BC_ICMS",
        "Coluna_17": "VL_ICMS",
        "Coluna_18": "VL_RED_BC",
        "Coluna_19": "COD_OBS",
        "Coluna_20": "COD_CTA"
    },
    "D301": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_DOC_CANC"
    },
    "D310": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MUN_ORIG",
        "Coluna_3": "VL_SERV",
        "Coluna_4": "VL_BC_ICMS",
        "Coluna_5": "VL_ICMS"
    },
    "D350": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "ECF_MOD",
        "Coluna_4": "ECF_FAB",
        "Coluna_5": "ECF_CX"
    },
    "D355": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_DOC",
        "Coluna_3": "CRO",
        "Coluna_4": "CRZ",
        "Coluna_5": "NUM_COO_FIN",
        "Coluna_6": "GT_FIN",
        "Coluna_7": "VL_BRT"
    },
    "D360": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_PIS",
        "Coluna_3": "VL_COFINS"
    },
    "D365": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_TOT_PAR",
        "Coluna_3": "VLR_ACUM_TOT",
        "Coluna_4": "NR_TOT",
        "Coluna_5": "DESCR_NR_TOT"
    },
    "D370": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MUN_ORIG",
        "Coluna_3": "VL_SERV",
        "Coluna_4": "QTD_BILH",
        "Coluna_5": "VL_BC_ICMS",
        "Coluna_6": "VL_ICMS"
    },
    "D390": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ISSQN",
        "Coluna_7": "ALIQ_ISSQN",
        "Coluna_8": "VL_ISSQN",
        "Coluna_9": "VL_BC_ICMS",
        "Coluna_10": "VL_ICMS",
        "Coluna_11": "COD_OBS"
    },
    "D400": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PART",
        "Coluna_3": "COD_MOD",
        "Coluna_4": "COD_SIT",
        "Coluna_5": "SER",
        "Coluna_6": "SUB",
        "Coluna_7": "NUM_DOC",
        "Coluna_8": "DT_DOC",
        "Coluna_9": "VL_DOC",
        "Coluna_10": "VL_DESC",
        "Coluna_11": "VL_SERV",
        "Coluna_12": "VL_BC_ICM S",
        "Coluna_13": "VL_ICMS",
        "Coluna_14": "VL_PIS",
        "Coluna_15": "VL_COFINS",
        "Coluna_16": "COD_CTA"
    },
    "D410": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "SER",
        "Coluna_4": "SUB",
        "Coluna_5": "NUM_DOC_INI",
        "Coluna_6": "NUM_DOC_FIN",
        "Coluna_7": "DT_DOC",
        "Coluna_8": "CST_ICMS",
        "Coluna_9": "CFOP",
        "Coluna_10": "ALIQ_ICMS",
        "Coluna_11": "VL_OPR",
        "Coluna_12": "VL_DESC",
        "Coluna_13": "VL_SERV",
        "Coluna_14": "VL_BC_ICMS",
        "Coluna_15": "VL_ICMS"
    },
    "D411": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_DOC_CANC"
    },
    "D420": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MUN_ORIG",
        "Coluna_3": "VL_SERV",
        "Coluna_4": "VL_BC_ICMS",
        "Coluna_5": "VL_ICMS"
    },
    "D500": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_OPER",
        "Coluna_3": "IND_EMIT",
        "Coluna_4": "COD_PART",
        "Coluna_5": "COD_MOD",
        "Coluna_6": "COD_SIT",
        "Coluna_7": "SER",
        "Coluna_8": "SUB",
        "Coluna_9": "NUM_DOC",
        "Coluna_10": "DT_DOC",
        "Coluna_11": "DT_A_P",
        "Coluna_12": "VL_DOC",
        "Coluna_13": "VL_DESC",
        "Coluna_14": "VL_SERV",
        "Coluna_15": "VL_SERV_NT",
        "Coluna_16": "VL_TERC",
        "Coluna_17": "VL_DA",
        "Coluna_18": "VL_BC_ICMS",
        "Coluna_19": "VL_ICMS",
        "Coluna_20": "COD_INF",
        "Coluna_21": "VL_PIS",
        "Coluna_22": "VL_COFINS",
        "Coluna_23": "COD_CTA",
        "Coluna_24": "TP_ASSINANTE"
    },
    "D510": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_ITEM",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "COD_CLASS",
        "Coluna_5": "QTD",
        "Coluna_6": "UNID",
        "Coluna_7": "VL_ITEM",
        "Coluna_8": "VL_DESC",
        "Coluna_9": "CST_ICMS",
        "Coluna_10": "CFOP",
        "Coluna_11": "VL_BC_ICMS",
        "Coluna_12": "ALIQ_ICMS",
        "Coluna_13": "VL_ICMS",
        "Coluna_14": "VL_BC_ICMS_UF",
        "Coluna_15": "VL_ICMS_UF",
        "Coluna_16": "IND_REC",
        "Coluna_17": "COD_PART",
        "Coluna_18": "VL_PIS",
        "Coluna_19": "VL_COFINS",
        "Coluna_20": "COD_CTA"
    },
    "D530": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_SERV",
        "Coluna_3": "DT_INI_SERV",
        "Coluna_4": "DT_FIN_SERV",
        "Coluna_5": "PER_FISCAL",
        "Coluna_6": "COD_AREA",
        "Coluna_7": "TERMINAL"
    },
    "D590": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_BC_ICMS_UF",
        "Coluna_9": "VL_ICMS_UF",
        "Coluna_10": "VL_RED_BC",
        "Coluna_11": "COD_OBS"
    },
    "D600": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "COD_MUN",
        "Coluna_4": "SER",
        "Coluna_5": "SUB",
        "Coluna_6": "COD_CONS",
        "Coluna_7": "QTD_CONS",
        "Coluna_8": "DT_DOC",
        "Coluna_9": "VL_DOC",
        "Coluna_10": "VL_DESC",
        "Coluna_11": "VL_SERV",
        "Coluna_12": "VL_SERV_NT",
        "Coluna_13": "VL_TERC",
        "Coluna_14": "VL_DA",
        "Coluna_15": "VL_BC_ICMS",
        "Coluna_16": "VL_ICMS",
        "Coluna_17": "VL_PIS",
        "Coluna_18": "VL_COFINS"
    },
    "D610": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_CLASS",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "QTD",
        "Coluna_5": "UNID",
        "Coluna_6": "VL_ITEM",
        "Coluna_7": "VL_DESC",
        "Coluna_8": "CST_ICMS",
        "Coluna_9": "CFOP",
        "Coluna_10": "ALIQ_ICMS",
        "Coluna_11": "VL_BC_ICMS",
        "Coluna_12": "VL_ICMS",
        "Coluna_13": "VL_BC_ICMS_UF",
        "Coluna_14": "VL_ICMS_UF",
        "Coluna_15": "VL_RED_BC",
        "Coluna_16": "VL_PIS",
        "Coluna_17": "VL_COFINS",
        "Coluna_18": "COD_CTA"
    },
    "D690": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_BC_ICMS_UF",
        "Coluna_9": "VL_ICMS_UF",
        "Coluna_10": "VL_RED_BC",
        "Coluna_11": "COD_OBS"
    },
    "D695": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "SER",
        "Coluna_4": "NRO_ORD_INI",
        "Coluna_5": "NRO_ORD_FIN",
        "Coluna_6": "DT_DOC_INI",
        "Coluna_7": "DT_DOC_FIN",
        "Coluna_8": "NOM_MEST",
        "Coluna_9": "CHV_COD_DIG"
    },
    "D696": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_BC_ICMS_ UF",
        "Coluna_9": "VL_ICMS_UF",
        "Coluna_10": "VL_RED_BC",
        "Coluna_11": "COD_OBS"
    },
    "D697": {
        "Coluna_1": "REG",
        "Coluna_2": "UF",
        "Coluna_3": "VL_BC_ICMS",
        "Coluna_4": "VL_ICMS",
        "Coluna_5": "DT_E_S",
        "Coluna_6": "VL_DOC",
        "Coluna_7": "VL_DESC",
        "Coluna_8": "VL_SERV",
        "Coluna_9": "VL_SERV_NT",
        "Coluna_10": "VL_TERC",
        "Coluna_11": "VL_DA",
        "Coluna_12": "VL_BC_ICMS",
        "Coluna_13": "VL_ICMS",
        "Coluna_14": "COD_INF",
        "Coluna_15": "VL_PIS",
        "Coluna_16": "VL_COFINS",
        "Coluna_17": "CHV_DOCe",
        "Coluna_18": "FIN_DOCe",
        "Coluna_19": "TIP_FAT",
        "Coluna_20": "COD_MOD_DOC_REF",
        "Coluna_21": "CHV_DOCe_REF",
        "Coluna_22": "HASH_DOC_REF",
        "Coluna_23": "SER_DOC_REF",
        "Coluna_24": "NUM_DOC_REF",
        "Coluna_25": "MES_DOC_REF",
        "Coluna_26": "COD_MUN_DEST"
    },
    "D73": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_RED_BC",
        "Coluna_9": "COD_OBS"
    },
    "D731": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_FCP_OP"
    },
    "D735": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_OBS",
        "Coluna_3": "TXT_COMPL"
    },
    "D737": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_AJ",
        "Coluna_3": "DESCR_COMPL_AJ",
        "Coluna_4": "COD_ITEM",
        "Coluna_5": "VL_BC_ICMS",
        "Coluna_6": "ALIQ_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_OUTROS"
    },
    "D750": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_MOD",
        "Coluna_3": "SER",
        "Coluna_4": "DT_DOC",
        "Coluna_5": "QTD_CONS",
        "Coluna_6": "IND_PREPAGO",
        "Coluna_7": "VL_DOC",
        "Coluna_8": "VL_SERV",
        "Coluna_9": "VL_",
        "Coluna_10": "VL_",
        "Coluna_11": "VL_",
        "Coluna_12": "VL_",
        "Coluna_13": "VL_",
        "Coluna_14": "VL_",
        "Coluna_15": "VL_",
        "Coluna_16": "VL_"
    },
    "D760": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "CFOP",
        "Coluna_4": "ALIQ_ICMS",
        "Coluna_5": "VL_OPR",
        "Coluna_6": "VL_BC_ICMS",
        "Coluna_7": "VL_ICMS",
        "Coluna_8": "VL_RED_BC",
        "Coluna_9": "COD_OBS"
    },
    "D761": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_FCP_OP"
    },
    "D990": {
        "Coluna_1": "REG",
        "Coluna_2": "QTD_LIN_D"
    },
    "E001": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_MOV"
    },
    "E100": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_INI",
        "Coluna_3": "DT_FIN"
    },
    "E110": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_TOT_DEBITOS",
        "Coluna_3": "VL_AJ_DEBITOS",
        "Coluna_4": "VL_TOT_AJ_DEBITOS",
        "Coluna_5": "VL_ESTORNOS_CRED",
        "Coluna_6": "VL_TOT_CREDITOS",
        "Coluna_7": "VL_AJ_CREDITOS",
        "Coluna_8": "VL_TOT_AJ_CREDITOS",
        "Coluna_9": "VL_ESTORNOS_DEB",
        "Coluna_10": "VL_SLD_CREDOR_ANT",
        "Coluna_11": "VL_SLD_APURADO",
        "Coluna_12": "VL_TOT_DED",
        "Coluna_13": "VL_ICMS_RECOLHER",
        "Coluna_14": "VL_SLD_CREDOR_TRA NSPORTAR",
        "Coluna_15": "DEB_ESP"
    },
    "E111": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_AJ_APUR",
        "Coluna_3": "DESCR_COMPL_AJ",
        "Coluna_4": "VL_AJ_APUR"
    },
    "E112": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_DA",
        "Coluna_3": "NUM_PROC",
        "Coluna_4": "IND_PROC",
        "Coluna_5": "PROC",
        "Coluna_6": "TXT_COMPL"
    },
    "E113": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PART",
        "Coluna_3": "COD_MOD",
        "Coluna_4": "SER",
        "Coluna_5": "SUB",
        "Coluna_6": "NUM_DOC",
        "Coluna_7": "DT_DOC",
        "Coluna_8": "COD_ITEM",
        "Coluna_9": "VL_AJ_ITEM",
        "Coluna_10": "CHV_DOCe"
    },
    "E115": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_INF_ADIC",
        "Coluna_3": "VL_INF_ADIC",
        "Coluna_4": "DESCR_COMPL_AJ"
    },
    "E116": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_OR",
        "Coluna_3": "VL_OR",
        "Coluna_4": "DT_VCTO",
        "Coluna_5": "COD_REC",
        "Coluna_6": "NUM_PROC",
        "Coluna_7": "IND_PROC",
        "Coluna_8": "PROC",
        "Coluna_9": "TXT_COMPL",
        "Coluna_10": "MES_REF*"
    },
    "E200": {
        "Coluna_1": "REG",
        "Coluna_2": "UF",
        "Coluna_3": "DT_INI",
        "Coluna_4": "DT_FIN"
    },
    "E210": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_MOV_ST",
        "Coluna_3": "VL_SLD_CRED_ANT_ST",
        "Coluna_4": "VL_DEVOL_ST",
        "Coluna_5": "VL_RESSARC_ST",
        "Coluna_6": "VL_OUT_CRED_ST",
        "Coluna_7": "VL_AJ_CREDITOS_ST",
        "Coluna_8": "VL_RETEN\u00c7AO_ST",
        "Coluna_9": "VL_OUT_DEB_ST",
        "Coluna_10": "VL_AJ_DEBITOS_ST",
        "Coluna_11": "VL_SLD_DEV_ANT_ST",
        "Coluna_12": "VL_DEDU\u00c7\u00d5ES_ST",
        "Coluna_13": "VL_ICMS_RECOL_ST",
        "Coluna_14": "VL_SLD_CRED_ST_TRANS PORTAR",
        "Coluna_15": "DEB_ESP_ST"
    },
    "E220": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_AJ_APUR",
        "Coluna_3": "DESCR_COMPL_AJ",
        "Coluna_4": "VL_AJ_APUR"
    },
    "E230": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_DA",
        "Coluna_3": "NUM_PROC",
        "Coluna_4": "IND_PROC",
        "Coluna_5": "PROC",
        "Coluna_6": "TXT_COMPL"
    },
    "E240": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PART",
        "Coluna_3": "COD_MOD",
        "Coluna_4": "SER",
        "Coluna_5": "SUB",
        "Coluna_6": "NUM_DOC",
        "Coluna_7": "DT_DOC",
        "Coluna_8": "COD_ITEM",
        "Coluna_9": "VL_AJ_ITEM",
        "Coluna_10": "CHV_DOCe"
    },
    "E250": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_OR",
        "Coluna_3": "VL_OR",
        "Coluna_4": "DT_VCTO",
        "Coluna_5": "COD_REC",
        "Coluna_6": "NUM_PROC",
        "Coluna_7": "IND_PROC",
        "Coluna_8": "PROC",
        "Coluna_9": "TXT_COMPL",
        "Coluna_10": "MES_REF*"
    },
    "E300": {
        "Coluna_1": "REG",
        "Coluna_2": "UF",
        "Coluna_3": "DT_INI",
        "Coluna_4": "DT_FIN"
    },
    "E310": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_MOV_DIFAL",
        "Coluna_3": "IND_MOV_FCP_DIFAL",
        "Coluna_4": "VL_SLD_CRED_ANT_DIFAL",
        "Coluna_5": "VL_SLD_CRED_ANT_DIFAL",
        "Coluna_6": "VL_TOT_DEBITOS_DIFAL",
        "Coluna_7": "VL_TOT_DEBITOS_DIFAL",
        "Coluna_8": "VL_OUT_DEB_DIFAL",
        "Coluna_9": "VL_OUT_DEB_DIFAL",
        "Coluna_10": "VL_TOT_DEB_FCP",
        "Coluna_11": "VL_TOT_CREDITOS_DIFAL",
        "Coluna_12": "VL_TOT_CREDITOS_DIFAL",
        "Coluna_13": "VL_OUT_CRED_DIFAL",
        "Coluna_14": "VL_TOT_CRED_FCP",
        "Coluna_15": "VL_SLD_DEV_ANT_DIFAL",
        "Coluna_16": "VL_OUT_CRED_DIFAL",
        "Coluna_17": "VL_DEDU\u00c7\u00d5ES_DIFAL",
        "Coluna_18": "VL_SLD_DEV_ANT_DIFAL",
        "Coluna_19": "VL_RECOL_DIFAL",
        "Coluna_20": "VL_DEDU\u00c7\u00d5ES_DIFAL",
        "Coluna_21": "VL_SLD_CRED_TRANSPORT AR_DIFAL",
        "Coluna_22": "VL_RECOL",
        "Coluna_23": "DEB_ESP_DIFAL",
        "Coluna_24": "VL_SLD_CRED_TRANSPOR TAR",
        "Coluna_25": "VL_SLD_CRED_ANT_FCP",
        "Coluna_26": "DEB_ESP_DIFAL",
        "Coluna_27": "VL_TOT_DEB_FCP",
        "Coluna_28": "VL_OUT_DEB_FCP",
        "Coluna_29": "VL_TOT_CRED_FCP",
        "Coluna_30": "VL_OUT_CRED_FCP",
        "Coluna_31": "VL_SLD_DEV_ANT_FCP",
        "Coluna_32": "VL_DEDU\u00c7\u00d5ES_FCP",
        "Coluna_33": "VL_RECOL_FCP",
        "Coluna_34": "VL_SLD_CRED_TRANSPORT AR_FCP",
        "Coluna_35": "DEB_ESP_FCP"
    },
    "E311": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_AJ_APUR",
        "Coluna_3": "DESCR_COMPL_AJ",
        "Coluna_4": "VL_AJ_APUR"
    },
    "E312": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_DA",
        "Coluna_3": "NUM_PROC",
        "Coluna_4": "IND_PROC",
        "Coluna_5": "PROC",
        "Coluna_6": "TXT_COMPL"
    },
    "E313": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PART",
        "Coluna_3": "COD_MOD",
        "Coluna_4": "SER",
        "Coluna_5": "SUB",
        "Coluna_6": "NUM_DOC",
        "Coluna_7": "CHV_DOCe",
        "Coluna_8": "DT_DOC",
        "Coluna_9": "COD_ITEM",
        "Coluna_10": "VL_AJ_ITEM"
    },
    "E316": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_OR",
        "Coluna_3": "VL_OR",
        "Coluna_4": "DT_VCTO",
        "Coluna_5": "COD_REC",
        "Coluna_6": "NUM_PROC",
        "Coluna_7": "IND_PROC",
        "Coluna_8": "PROC",
        "Coluna_9": "TXT_COMPL",
        "Coluna_10": "MES_REF*"
    },
    "E500": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_APUR",
        "Coluna_3": "DT_INI",
        "Coluna_4": "DT_FIN"
    },
    "E510": {
        "Coluna_1": "REG",
        "Coluna_2": "CFOP",
        "Coluna_3": "CST_IPI",
        "Coluna_4": "VL_CONT_IPI",
        "Coluna_5": "VL_BC_IPI",
        "Coluna_6": "VL_IPI"
    },
    "E520": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_SD_ANT_IPI",
        "Coluna_3": "VL_DEB_IPI",
        "Coluna_4": "VL_CRED_IPI",
        "Coluna_5": "VL_OD_IPI",
        "Coluna_6": "VL_OC_IPI",
        "Coluna_7": "VL_SC_IPI",
        "Coluna_8": "VL_SD_IPI"
    },
    "E530": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_AJ",
        "Coluna_3": "VL_AJ",
        "Coluna_4": "COD_AJ",
        "Coluna_5": "IND_DOC",
        "Coluna_6": "NUM_DOC",
        "Coluna_7": "DESCR_AJ"
    },
    "E531": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_PART",
        "Coluna_3": "COD_MOD",
        "Coluna_4": "SER",
        "Coluna_5": "SUB",
        "Coluna_6": "NUM_DOC",
        "Coluna_7": "DT_DOC",
        "Coluna_8": "COD_ITEM",
        "Coluna_9": "VL_AJ_ITEM",
        "Coluna_10": "CHV_NFE"
    },
    "G001": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_MOV"
    },
    "G110": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_INI",
        "Coluna_3": "DT_FIN",
        "Coluna_4": "SALDO_IN_ICMS",
        "Coluna_5": "SOM_PARC",
        "Coluna_6": "VL_TRIB_EXP",
        "Coluna_7": "VL_TOTAL",
        "Coluna_8": "IND_PER_SAI",
        "Coluna_9": "ICMS_APROP",
        "Coluna_10": "SOM_ICMS_OC"
    },
    "G125": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_IND_BEM",
        "Coluna_3": "DT_MOV",
        "Coluna_4": "TIPO_MOV",
        "Coluna_5": "VL_IMOB_ICMS_ OP",
        "Coluna_6": "VL_IMOB_ICMS_ ST",
        "Coluna_7": "VL_IMOB_ICMS_ FRT",
        "Coluna_8": "VL_IMOB_ICMS_ DIF",
        "Coluna_9": "NUM_PARC",
        "Coluna_10": "VL_PARC_PASS"
    },
    "G126": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_INI",
        "Coluna_3": "DT_FIM",
        "Coluna_4": "NUM_PARC",
        "Coluna_5": "VL_PARC_PASS",
        "Coluna_6": "VL_TRIB_OC",
        "Coluna_7": "VL_TOTAL",
        "Coluna_8": "IND_PER_SAI",
        "Coluna_9": "VL_PARC_APROP"
    },
    "G130": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_EMIT",
        "Coluna_3": "COD_PART",
        "Coluna_4": "COD_MOD",
        "Coluna_5": "SERIE",
        "Coluna_6": "NUM_DOC",
        "Coluna_7": "CHV_NFE_CTE",
        "Coluna_8": "DT_DOC",
        "Coluna_9": "NUM_DA"
    },
    "G140": {
        "Coluna_1": "REG",
        "Coluna_2": "NUM_ITEM",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "QTDE",
        "Coluna_5": "UNID",
        "Coluna_6": "VL_ICMS_OP_APLICADO",
        "Coluna_7": "VL_ICMS_ST_APLICADO",
        "Coluna_8": "VL_ICMS_FRT_APLICADO",
        "Coluna_9": "VL_ICMS_DIF_APLICADO"
    },
    "G990": {
        "Coluna_1": "REG",
        "Coluna_2": "QTD_LIN_G"
    },
    "H001": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_MOV"
    },
    "H005": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_INV",
        "Coluna_3": "VL_INV",
        "Coluna_4": "MOT_INV"
    },
    "H010": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM",
        "Coluna_3": "UNID",
        "Coluna_4": "QTD",
        "Coluna_5": "VL_UNIT",
        "Coluna_6": "VL_ITEM",
        "Coluna_7": "IND_PROP",
        "Coluna_8": "COD_PART",
        "Coluna_9": "TXT_COMPL",
        "Coluna_10": "COD_CTA",
        "Coluna_11": "VL_ITEM_IR"
    },
    "H020": {
        "Coluna_1": "REG",
        "Coluna_2": "CST_ICMS",
        "Coluna_3": "BC_ICMS",
        "Coluna_4": "VL_ICMS"
    },
    "H030": {
        "Coluna_1": "REG",
        "Coluna_2": "VL_ICMS_OP",
        "Coluna_3": "VL_BC_ICMS_ST",
        "Coluna_4": "VL_ICMS_ST",
        "Coluna_5": "VL_FCP"
    },
    "H990": {
        "Coluna_1": "REG",
        "Coluna_2": "QTD_LIN_H"
    },
    "K001": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_MOV"
    },
    "K010": {
        "Coluna_1": "REG",
        "Coluna_2": "IND_TP_LEIAUTE"
    },
    "K100": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_INI",
        "Coluna_3": "DT_FIN"
    },
    "K200": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_EST",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "QTD",
        "Coluna_5": "IND_EST",
        "Coluna_6": "COD_PART"
    },
    "K210": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_INI_OS",
        "Coluna_3": "DT_FIN_OS",
        "Coluna_4": "COD_DOC_OS",
        "Coluna_5": "COD_ITEM_ORI",
        "Coluna_6": "QTD_ORI"
    },
    "K215": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM_DES",
        "Coluna_3": "QTD_DES"
    },
    "K220": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_MOV",
        "Coluna_3": "COD_ITEM_ORI",
        "Coluna_4": "COD_ITEM_DEST",
        "Coluna_5": "QTD_ORI",
        "Coluna_6": "QTD_DEST"
    },
    "K230": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_INI_OP",
        "Coluna_3": "DT_FIN_OP",
        "Coluna_4": "COD_DOC_OP",
        "Coluna_5": "COD_ITEM",
        "Coluna_6": "QTD_ENC"
    },
    "K235": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_SA\u00cdDA",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "QTD",
        "Coluna_5": "COD_INS_SUBS T"
    },
    "K250": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_PROD",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "QTD"
    },
    "K255": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_CONS",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "QTD",
        "Coluna_5": "COD_INS_SUBS T"
    },
    "K260": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_OP_OS",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "DT_SA\u00cdDA",
        "Coluna_5": "QTD_SA\u00cdDA",
        "Coluna_6": "DT_RET",
        "Coluna_7": "QTD_RET"
    },
    "K265": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM",
        "Coluna_3": "QTD_CONS",
        "Coluna_4": "QTD_RET"
    },
    "K270": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_INI_AP",
        "Coluna_3": "DT_FIN_AP",
        "Coluna_4": "COD_OP_OS",
        "Coluna_5": "COD_ITEM",
        "Coluna_6": "QTD_COR_POS",
        "Coluna_7": "QTD_COR_NEG",
        "Coluna_8": "ORIGEM"
    },
    "K275": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM",
        "Coluna_3": "QTD_COR_POS",
        "Coluna_4": "QTD_COR_NEG",
        "Coluna_5": "COD_INS_SUBST"
    },
    "K280": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_EST",
        "Coluna_3": "COD_ITEM",
        "Coluna_4": "QTD_COR_POS",
        "Coluna_5": "QTD_COR_NEG",
        "Coluna_6": "IND_EST",
        "Coluna_7": "COD_PART"
    },
    "K290": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_INI_OP",
        "Coluna_3": "DT_FIN_OP",
        "Coluna_4": "COD_DOC_OP"
    },
    "K291": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM",
        "Coluna_3": "QTD"
    },
    "K292": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM",
        "Coluna_3": "QTD"
    },
    "K300": {
        "Coluna_1": "REG",
        "Coluna_2": "DT_PROD"
    },
    "K301": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM",
        "Coluna_3": "QTD"
    },
    "K302": {
        "Coluna_1": "REG",
        "Coluna_2": "COD_ITEM",
        "Coluna_3": "QTD"
    },
    "K990": {
        "Coluna_1": "REG",
        "Coluna_2": "QTD_LIN_K"
    }
}